#!/bin/bash

cd "$(dirname "$0")"
cd ..

# Reads .env files (from the basedirectory of the bare repo running the hook)
if [ -z "${-%%*a*}" ]; then
    set -a
    . ./.env
    set +a
else
    . ./.env
fi

NODEV=$(node -v)
YARNV=$(yarn -v)

build () {
	yarn install
	yarn $1
}

while read oldrev newrev ref
do
    if [ -z $ref ]; then
        echo "No ref set. Exisitng."
        exit 1
    else
        if [ "$ref" = "refs/heads/production" ]; then
            BRANCH="production"
            CMD="build"
        elif [ "$ref" = "refs/heads/staging" ]; then
            BRANCH="staging"
            CMD="build-staging"
        elif [ "$ref" = "refs/heads/development" ]; then
            BRANCH="development"
            CMD="build-dev"
        else
            echo "Ref ($ref) doesnt match production, staging, or development, exisitng."
            exit 1
        fi

        echo ░█▀▄░█▀▀░█▀█░█░░░█▀█░█░█░▀█▀░█▀█░█▀▀
        echo ░█░█░█▀▀░█▀▀░█░░░█░█░░█░░░█░░█░█░█░█
        echo ░▀▀░░▀▀▀░▀░░░▀▀▀░▀▀▀░░▀░░▀▀▀░▀░▀░▀▀▀
        echo ░█░█░█▀█░█▀▄░█▀█░▀█▀░█▀▀░█▀▄
        echo ░█░█░█▀▀░█░█░█▀█░░█░░█▀▀░█░█
        echo ░▀▀▀░▀░░░▀▀░░▀░▀░░▀░░▀▀▀░▀▀░
        echo ░█▀█░█░░░█░█░█▀▀░▀█▀░█▀█
        echo ░█▀▀░█░░░█░█░█░█░░█░░█░█
        echo ░▀░░░▀▀▀░▀▀▀░▀▀▀░▀▀▀░▀░▀
        echo "-------------------------------------------------------------------------------"
        echo "Running deployment script for ${SITE_NAME}"
        echo "-------------------------------------------------------------------------------"
        cd $ASTRO_SOURCE
        git --work-tree=$PLUGIN_SOURCE --git-dir=$GIT_DIR checkout -f $BRANCH
        build $CMDt
        exit 0
    fi
done
